# Generated by Django 2.0.3 on 2018-04-03 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20180403_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipo_habitacion',
            old_name='nombre',
            new_name='habitacion',
        ),
        migrations.AddField(
            model_name='tipo_habitacion',
            name='anio',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipo_habitacion',
            name='cant_habitacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipo_habitacion',
            name='id_hotel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipo_habitacion',
            name='mes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tipo_habitacion',
            name='total_habitacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 16, 5, 59, 804095), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_eliminacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 16, 5, 59, 804095), verbose_name='date published'),
        ),
    ]
