# Generated by Django 2.0.3 on 2018-04-03 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20180403_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='suma_habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hotel', models.IntegerField(default=0)),
                ('anio', models.IntegerField(default=0)),
                ('mes', models.IntegerField(default=0)),
                ('habitacion', models.CharField(default='SOME STRING', max_length=200)),
                ('cant_habitacion', models.IntegerField(default=0)),
                ('total_habitacion', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tipo_habitacion',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='tipo_habitacion',
            name='cant_habitacion',
        ),
        migrations.RemoveField(
            model_name='tipo_habitacion',
            name='habitacion',
        ),
        migrations.RemoveField(
            model_name='tipo_habitacion',
            name='id_hotel',
        ),
        migrations.RemoveField(
            model_name='tipo_habitacion',
            name='mes',
        ),
        migrations.RemoveField(
            model_name='tipo_habitacion',
            name='total_habitacion',
        ),
        migrations.AddField(
            model_name='tipo_habitacion',
            name='nombre',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 16, 8, 15, 835922), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_eliminacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 16, 8, 15, 835922), verbose_name='date published'),
        ),
    ]
