# Generated by Django 2.0.3 on 2018-04-03 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20180403_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suma_habitacion',
            old_name='cant_habitacion',
            new_name='numero_facturas',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 16, 51, 22, 786846), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_eliminacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 16, 51, 22, 786846), verbose_name='date published'),
        ),
    ]
