# Generated by Django 2.0.3 on 2018-04-04 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20180403_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas_totales',
            name='Brasil',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='Colombia',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='Ecuador',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='Espania',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='Italia',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='Mexico',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='Peru',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='Venezuela',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='cliente',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='normal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='salon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ventas_totales',
            name='suit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 20, 25, 29, 567252), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_eliminacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 3, 20, 25, 29, 567252), verbose_name='date published'),
        ),
    ]
