# Generated by Django 2.0.3 on 2018-04-05 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20180403_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas_totales',
            name='Extranjeros',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 22, 42, 44, 124620), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_eliminacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 22, 42, 44, 124620), verbose_name='date published'),
        ),
    ]
