# Generated by Django 2.0.3 on 2018-04-05 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20180404_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='nacionalesextranjeros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hotel', models.IntegerField(default=0)),
                ('anio', models.IntegerField(default=0)),
                ('Italia', models.CharField(default='SOME STRING', max_length=200)),
                ('Espania', models.CharField(default='SOME STRING', max_length=200)),
                ('Ecuador', models.CharField(default='SOME STRING', max_length=200)),
                ('Mexico', models.CharField(default='SOME STRING', max_length=200)),
                ('Brasil', models.CharField(default='SOME STRING', max_length=200)),
                ('Peru', models.CharField(default='SOME STRING', max_length=200)),
                ('Colombia', models.CharField(default='SOME STRING', max_length=200)),
                ('Venezuela', models.CharField(default='SOME STRING', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 0, 10, 31, 605756), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_eliminacion',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 5, 0, 10, 31, 605756), verbose_name='date published'),
        ),
    ]
